##########################################################################################
# Gemini settings
##########################################################################################
[gemini]

# Your Gemini API Key
key = "YOUR_GEMINI_API_KEY" 

# The model to use for Gemini
model = "gemini-1.5-flash"

# the path to the prompt
prompt = "../prompts/gemini_prompt_framing.txt"



##########################################################################################
# OpenAI settings
##########################################################################################
[openai]

# Your OpenAI API Key
key = "YOUR_OPENAI_API_KEY" 

# The model to use for OpenAI audio transcription
model = "whisper-1"



##########################################################################################
# paths
##########################################################################################
[paths]

# Path for all project data except for media files (temp and backup dirs end up here as well)
main = "/ABSOLUTE/PATH/TO/YOUR/DATA/" 

# Path to your Firefox Downloads folder
firefox_downloads = "/Users/YOURUSERNAME/Downloads"



##########################################################################################
# misc settings
##########################################################################################
[misc]

# this label is added to zeeschuimer ndjson files in the zeeschuimer_raw folder
label = "no_label" 



##########################################################################################
# settings for the media storage
##########################################################################################
[media_storage]

# Should media be stored locally or in a GCP bucket? ['local' or 'GCP']
storage_type = "local" 

# The name of your GCP bucket for storage of video audio files
GCP_bucket = "YOUR_GCP_BUCKET_NAME" 

# The absolute path to your local storage if you prefer that to GCP
local_storage_dir= "/ABSOLUTE/PATH/TO/YOUR/DATA/media/"  

