# You shouldn't have to change these parameters. Ever.



##########################################################################################
# Gemini settings
##########################################################################################
[gemini]
# The timeout for Gemini. It times out after this many seconds. Almost never happens.
timeout = 30

# The temperature controls the randomness of the model's output, with higher values
# leading to more diverse responses and lower values making outputs more focused and deterministic.
# I have set it very low to make the output more deterministic and focused.
temperature = 0.4

# The model will consider only the smallest group of words whose combined probabilities add up to 95%. 
# It focuses on the most likely words but allows some diversity by including multiple options.
# Note that top_p has reduced impact when the temperature is set very low. (like 0.1)
top_p = 0.95

# The model will only consider the top 64 most likely words when choosing the next word.
# It limits the choices to the 64 best options, ensuring a balance between quality and variety.
# Note that top_k has reduced impact when the temperature is set very low. (like 0.1)
top_k = 64

# the maximum number of tokens to output. This should be plenty!
max_output_tokens = 8192

# check the quality of the LLM output in these columns and re-process the videos if the results don't meet requirements
doublecheck_these_cols = ["video_story", "text_visible_in_video", "list_of_objects_in_video"] 

# verbose flag for all gemini functions
verbose = false





##########################################################################################
# Gemini Finish Reasons
##########################################################################################
[gemini_finish_reason]
FINISH_REASON_UNSPECIFIED = 0    # The finish reason is unspecified.
STOP = 1                         # Token generation reached a natural stopping point or a configured stop sequence.
MAX_TOKENS = 2                   # Token generation reached the configured maximum output tokens.
SAFETY = 3                       # Token generation stopped because the content potentially contains safety violations. NOTE: When streaming, content is empty if content filters blocks the output.
RECITATION = 4                   # Token generation stopped because the content potentially contains copyright violations.
OTHER = 5                        # All other reasons that stopped the token generation.
BLOCKLIST = 6                    # Token generation stopped because the content contains forbidden terms.
PROHIBITED_CONTENT = 7           # Token generation stopped for potentially containing prohibited content.
SPII = 8                         # Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
MALFORMED_FUNCTION_CALL = 9      # The function call generated by the model is invalid.






##########################################################################################
# these files are all located in the main data folder
##########################################################################################
[fn]

# All DFs in zeeschuimer_refined concatenated into one big DF - and some columns dropped.
baseline_results_fn = "baseline.csv" 

# The data donation packages, filtered for words that the user doesn't want to include, and expanded w other useful metadata
ddp_results_fn = "ddp_results.csv" 

# metadata generated by PykTok. This is the main table to keep track of all static project data
pyk_metadata_fn = "pyk_metadata.pkl" 

# items that could not be downloaded by PykTok
pyk_failed_items_fn = "pyk_failed_items.json" 

 # the LLM analysis results from Gemini
gemini_video_analysis_fn = "gemini_video_analysis.pkl"

# the audio transcriptions
audio_transcriptions_fn = "audio_transcriptions.json" 

# all static video metadata from the videos
all_static_metadata_fn = "all_static_metadata.csv" 

# metadata to drive the FYP website
website_metadata_fn = "website_metadata.csv" 




##########################################################################################
# settings for the media storage
##########################################################################################
[media_storage]
# prefix/folder for videos - sitting in the top level of the media storage
video_prefix = "videos" 

# prefix/folder for audio files - sitting in the top level of the media storage
audio_prefix = "extracted_audio" 

# prefix/folder for video covers - sitting in the top level of the media storage
video_cover_prefix = "video_covers" 





